name: Check Android build

on:
  push:
    branches: [ main, dev/main ]
  pull_request:
    branches: [ main, dev/main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android NDK and CMake
        run: |
          sdkmanager "ndk;25.1.8937393" "cmake;3.22.1"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run all the Unit tests
        run: ./gradlew test --continue --stacktrace

      - name: Upload possible failed Unit-test reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-reports
          path: '**/build/reports/tests/'
  
      - name: Check application build
        if: always()
        run: ./gradlew assembleDebug --stacktrace

      
